const img = (id) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1800&q=80`;

export const catalog = [
  {
    name: "BMW",
    country: "Germany",
    description: "Precision engineering with a motorsport heartbeat. BMW on REVORA covers M cars from daily drivers to Competition machines.",
    models: [
      {
        name: "M3",
        generations: [
          {
            name: "G80",
            yearStart: 2021,
            cars: [
              {
                trim: "M3 Competition xDrive",
                year: 2024,
                bodyType: "Sedan",
                engine: "S58 3.0L Twin-Turbo I6",
                displacement: 3.0,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "AWD",
                horsepower: 503,
                torque: 650,
                zeroToHundred: 3.5,
                topSpeed: 290,
                weight: 1780,
                dimensions: { length: 4794, width: 1903, height: 1437 },
                images: [img("photo-1555215695-3004980ad54e"), img("photo-1617531653332-bd46c24f2068")],
                description: "The G80 M3 Competition is the current M benchmark: brutal midrange, xDrive traction, and a cabin built around the driver.",
                features: ["M Drive Professional", "Carbon bucket seats", "Laser headlights", "Track mode"],
              },
            ],
          },
        ],
      },
      {
        name: "M4",
        generations: [
          {
            name: "G82",
            yearStart: 2021,
            cars: [
              {
                trim: "M4 Competition",
                year: 2024,
                bodyType: "Coupe",
                engine: "S58 3.0L Twin-Turbo I6",
                displacement: 3.0,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "RWD",
                horsepower: 503,
                torque: 650,
                zeroToHundred: 3.9,
                topSpeed: 290,
                weight: 1725,
                dimensions: { length: 4794, width: 1887, height: 1393 },
                images: [img("photo-1617531653332-bd46c24f2068"), img("photo-1555215695-3004980ad54e")],
                description: "Two-door M4 Competition: the same S58 fury as the M3, with a lower visual mass and a more focused coupe stance.",
                features: ["M Carbon exterior", "Adaptive M suspension", "Head-up display"],
              },
            ],
          },
        ],
      },
      {
        name: "M5",
        generations: [
          {
            name: "F90",
            yearStart: 2018,
            yearEnd: 2023,
            cars: [
              {
                trim: "M5 CS",
                year: 2022,
                bodyType: "Sedan",
                engine: "S63 4.4L Twin-Turbo V8",
                displacement: 4.4,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "AWD",
                horsepower: 627,
                torque: 750,
                zeroToHundred: 3.0,
                topSpeed: 305,
                weight: 1825,
                dimensions: { length: 4983, width: 1903, height: 1467 },
                images: [img("photo-1617531657526-066ba8ae0d3d"), img("photo-1555215695-3004980ad54e")],
                description: "The rare F90 M5 CS is a homologation-feeling super saloon: gold wheels, carbon, and a V8 that never sounds finished.",
                features: ["CS aero", "Carbon roof", "Gold bronze wheels"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Mercedes-Benz",
    country: "Germany",
    description: "AMG performance with grand-tourer presence. From C63 to GT, Mercedes on REVORA is about controlled violence.",
    models: [
      {
        name: "C-Class",
        generations: [
          {
            name: "W206",
            yearStart: 2022,
            cars: [
              {
                trim: "AMG C63 S E Performance",
                year: 2024,
                bodyType: "Sedan",
                engine: "M139l 2.0L Turbo PHEV I4",
                displacement: 2.0,
                fuelType: "Plug-in Hybrid",
                transmission: "Automatic",
                driveType: "AWD",
                horsepower: 671,
                torque: 1020,
                zeroToHundred: 3.4,
                topSpeed: 280,
                weight: 2111,
                dimensions: { length: 4841, width: 1900, height: 1458 },
                images: [img("photo-1618843479313-40f8afb4b4d8"), img("photo-1617814076367-b759c7d7e738")],
                description: "The new C63 trades the V8 for a Formula-inspired hybrid four. Controversial, explosive, and uniquely AMG.",
                features: ["P3 hybrid system", "Drift mode", "AMG Track Pace"],
              },
            ],
          },
        ],
      },
      {
        name: "AMG GT",
        generations: [
          {
            name: "X290",
            yearStart: 2018,
            cars: [
              {
                trim: "GT 63 S 4MATIC+",
                year: 2023,
                bodyType: "Sedan",
                engine: "M177 4.0L Twin-Turbo V8",
                displacement: 4.0,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "AWD",
                horsepower: 630,
                torque: 900,
                zeroToHundred: 3.2,
                topSpeed: 315,
                weight: 2045,
                dimensions: { length: 5054, width: 1953, height: 1447 },
                images: [img("photo-1617814076367-b759c7d7e738"), img("photo-1618843479313-40f8afb4b4d8")],
                description: "Four-door AMG GT 63 S: long-legged V8 muscle with a cabin that still feels like a private jet.",
                features: ["AMG Ride Control", "Burmester 3D", "Rear-axle steering"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Porsche",
    country: "Germany",
    description: "The reference sports car. Carrera for the road, GT3 for the circuit — both belong in a REVORA garage.",
    models: [
      {
        name: "911",
        generations: [
          {
            name: "992",
            yearStart: 2019,
            cars: [
              {
                trim: "Carrera S",
                year: 2024,
                bodyType: "Coupe",
                engine: "3.0L Twin-Turbo Flat-6",
                displacement: 3.0,
                fuelType: "Petrol",
                transmission: "DCT",
                driveType: "RWD",
                horsepower: 443,
                torque: 530,
                zeroToHundred: 3.7,
                topSpeed: 308,
                weight: 1515,
                dimensions: { length: 4519, width: 1852, height: 1298 },
                images: [img("photo-1503376780353-7e6692767b70"), img("photo-1614162692292-bd138b0e6e0c")],
                description: "The everyday 911. Turbocharged flat-six, PDK, and a chassis that still teaches every other sports car manners.",
                features: ["PASM", "Sport Chrono", "Rear-axle steering"],
              },
              {
                trim: "GT3",
                year: 2023,
                bodyType: "Coupe",
                engine: "4.0L Naturally Aspirated Flat-6",
                displacement: 4.0,
                fuelType: "Petrol",
                transmission: "DCT",
                driveType: "RWD",
                horsepower: 502,
                torque: 440,
                zeroToHundred: 3.4,
                topSpeed: 318,
                weight: 1418,
                dimensions: { length: 4573, width: 1852, height: 1279 },
                images: [img("photo-1614162692292-bd138b0e6e0c"), img("photo-1503376780353-7e6692767b70")],
                description: "Motorsport 911 for the road. The 9,000-rpm NA six and a swan-neck wing that needs no explanation.",
                features: ["Double wishbone front", "Track-focused aero", "Carbon ceramic brakes"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Nissan",
    country: "Japan",
    description: "Godzilla and the Z. Nissan's performance story is turbocharged, AWD when it matters, and unapologetically analog.",
    models: [
      {
        name: "GT-R",
        generations: [
          {
            name: "R35",
            yearStart: 2007,
            yearEnd: 2025,
            cars: [
              {
                trim: "NISMO",
                year: 2024,
                bodyType: "Coupe",
                engine: "VR38DETT 3.8L Twin-Turbo V6",
                displacement: 3.8,
                fuelType: "Petrol",
                transmission: "DCT",
                driveType: "AWD",
                horsepower: 600,
                torque: 652,
                zeroToHundred: 2.7,
                topSpeed: 315,
                weight: 1752,
                dimensions: { length: 4710, width: 1895, height: 1370 },
                images: [img("photo-1544636331-e26879cd4d9b"), img("photo-1605559424843-9e4c228bf1c2")],
                description: "The last R35 NISMO. A 17-year legend with ATTESA AWD and a soundtrack that still fills a tunnel.",
                features: ["NISMO aero", "Bilstein DampTronic", "Recaro seats"],
              },
            ],
          },
        ],
      },
      {
        name: "Z",
        generations: [
          {
            name: "RZ34",
            yearStart: 2023,
            cars: [
              {
                trim: "Nismo",
                year: 2024,
                bodyType: "Coupe",
                engine: "VR30DDTT 3.0L Twin-Turbo V6",
                displacement: 3.0,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "RWD",
                horsepower: 420,
                torque: 520,
                zeroToHundred: 4.3,
                topSpeed: 250,
                weight: 1635,
                dimensions: { length: 4380, width: 1865, height: 1315 },
                images: [img("photo-1605559424843-9e4c228bf1c2"), img("photo-1544636331-e26879cd4d9b")],
                description: "Modern Z Nismo: wider stance, retuned VR30, and a cabin that still feels like a Japanese sports car should.",
                features: ["Nismo suspension", "Launch control", "Sport exhaust"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Toyota",
    country: "Japan",
    description: "Gazoo Racing turned Toyota into a driver's brand again. Supra and GR Yaris punch far above their size.",
    models: [
      {
        name: "Supra",
        generations: [
          {
            name: "A90",
            yearStart: 2019,
            cars: [
              {
                trim: "GR Supra 3.0",
                year: 2024,
                bodyType: "Coupe",
                engine: "B58 3.0L Turbo I6",
                displacement: 3.0,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "RWD",
                horsepower: 382,
                torque: 500,
                zeroToHundred: 4.1,
                topSpeed: 250,
                weight: 1540,
                dimensions: { length: 4380, width: 1865, height: 1295 },
                images: [img("photo-1632245889029-e406faaa34cd"), img("photo-1617531653332-bd46c24f2068")],
                description: "A90 GR Supra: BMW B58 in a Toyota body. Short wheelbase, long hood, and a chassis that loves to rotate.",
                features: ["Adaptive suspension", "Launch control", "Active rear spoiler"],
              },
            ],
          },
        ],
      },
      {
        name: "GR Yaris",
        generations: [
          {
            name: "XP21",
            yearStart: 2020,
            cars: [
              {
                trim: "Circuit Pack",
                year: 2024,
                bodyType: "Hatchback",
                engine: "G16E-GTS 1.6L Turbo I3",
                displacement: 1.6,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "AWD",
                horsepower: 276,
                torque: 390,
                zeroToHundred: 5.2,
                topSpeed: 230,
                weight: 1280,
                dimensions: { length: 3995, width: 1805, height: 1455 },
                images: [img("photo-1541899481282-d53bffcf8837"), img("photo-1632245889029-e406faaa34cd")],
                description: "A homologation special hiding as a supermarket hatch. GR-FOUR AWD and a three-cylinder that should not work this well.",
                features: ["GR-FOUR AWD", "Torsen diffs", "Forged wheels"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Ford",
    country: "United States",
    description: "American performance, from Dark Horse Mustangs to the halo Ford GT.",
    models: [
      {
        name: "Mustang",
        generations: [
          {
            name: "S650",
            yearStart: 2024,
            cars: [
              {
                trim: "Dark Horse",
                year: 2024,
                bodyType: "Coupe",
                engine: "5.0L Coyote V8",
                displacement: 5.0,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "RWD",
                horsepower: 500,
                torque: 567,
                zeroToHundred: 4.4,
                topSpeed: 270,
                weight: 1760,
                dimensions: { length: 4811, width: 1915, height: 1400 },
                images: [img("photo-1494976388531-d1058494cdd8"), img("photo-1552519507-da3b142c6e3d")],
                description: "The S650 Dark Horse is the enthusiast Mustang: cross-plane V8, Tremec manual, and a rear end that still talks to you.",
                features: ["MagneRide", "Tremec 6-speed", "Track apps"],
              },
            ],
          },
        ],
      },
      {
        name: "GT",
        generations: [
          {
            name: "Second Generation",
            yearStart: 2017,
            yearEnd: 2022,
            cars: [
              {
                trim: "GT",
                year: 2022,
                bodyType: "Coupe",
                engine: "3.5L Twin-Turbo EcoBoost V6",
                displacement: 3.5,
                fuelType: "Petrol",
                transmission: "DCT",
                driveType: "RWD",
                horsepower: 660,
                torque: 746,
                zeroToHundred: 2.9,
                topSpeed: 347,
                weight: 1385,
                dimensions: { length: 4763, width: 2004, height: 1110 },
                images: [img("photo-1552519507-da3b142c6e3d"), img("photo-1494976388531-d1058494cdd8")],
                description: "Le Mans silhouette for the road. Carbon everything, a mid-engine EcoBoost V6, and presence that stops traffic.",
                features: ["Active aero", "Carbon tub", "Pushrod suspension"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Ferrari",
    country: "Italy",
    description: "Maranello's current generation: hybrid V6 theatre and the last of the twin-turbo V8 mid-engine cars.",
    models: [
      {
        name: "296",
        generations: [
          {
            name: "296 GTB",
            yearStart: 2022,
            cars: [
              {
                trim: "GTB",
                year: 2024,
                bodyType: "Coupe",
                engine: "F163 3.0L Twin-Turbo V6 Hybrid",
                displacement: 3.0,
                fuelType: "Hybrid",
                transmission: "DCT",
                driveType: "RWD",
                horsepower: 818,
                torque: 740,
                zeroToHundred: 2.9,
                topSpeed: 330,
                weight: 1470,
                dimensions: { length: 4565, width: 1958, height: 1181 },
                images: [img("photo-1583121274602-3e2820c69888"), img("photo-1592198084033-aade902d1aae")],
                description: "The 296 GTB proves a V6 hybrid can still feel like Ferrari: 8500 rpm, electric fill-in, and a shape that looks carved.",
                features: ["Assetto Fiorano", "eManettino", "Active aero"],
              },
            ],
          },
        ],
      },
      {
        name: "F8",
        generations: [
          {
            name: "F8 Tributo",
            yearStart: 2019,
            yearEnd: 2023,
            cars: [
              {
                trim: "Tributo",
                year: 2022,
                bodyType: "Coupe",
                engine: "F154 3.9L Twin-Turbo V8",
                displacement: 3.9,
                fuelType: "Petrol",
                transmission: "DCT",
                driveType: "RWD",
                horsepower: 710,
                torque: 770,
                zeroToHundred: 2.9,
                topSpeed: 340,
                weight: 1435,
                dimensions: { length: 4611, width: 1977, height: 1206 },
                images: [img("photo-1592198084033-aade902d1aae"), img("photo-1583121274602-3e2820c69888")],
                description: "A tribute to Ferrari's twin-turbo V8 era. Brutal midrange, SSC, and an engine cover that is basically jewelry.",
                features: ["Side Slip Control", "F1-TCS", "Carbon racing seats"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Lamborghini",
    country: "Italy",
    description: "Sant'Agata theatre. Naturally aspirated V10 drama and the Urus as a super-SUV outlier.",
    models: [
      {
        name: "Huracán",
        generations: [
          {
            name: "LB724",
            yearStart: 2022,
            cars: [
              {
                trim: "Tecnica",
                year: 2023,
                bodyType: "Coupe",
                engine: "5.2L Naturally Aspirated V10",
                displacement: 5.2,
                fuelType: "Petrol",
                transmission: "DCT",
                driveType: "RWD",
                horsepower: 631,
                torque: 565,
                zeroToHundred: 3.2,
                topSpeed: 325,
                weight: 1379,
                dimensions: { length: 4567, width: 1933, height: 1165 },
                images: [img("photo-1525609004556-c46c7d6cf023"), img("photo-1519245659620-e859806a8d3b")],
                description: "The thinking Huracán. Rear-drive Tecnica sits between STO and EVO with a V10 that still revs like a superbike.",
                features: ["LDVI", "Rear-wheel steering", "ANIMA drive modes"],
              },
            ],
          },
        ],
      },
      {
        name: "Urus",
        generations: [
          {
            name: "Urus S",
            yearStart: 2022,
            cars: [
              {
                trim: "Urus S",
                year: 2024,
                bodyType: "SUV",
                engine: "4.0L Twin-Turbo V8",
                displacement: 4.0,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "AWD",
                horsepower: 657,
                torque: 850,
                zeroToHundred: 3.5,
                topSpeed: 305,
                weight: 2197,
                dimensions: { length: 5112, width: 2016, height: 1638 },
                images: [img("photo-1603584173870-7f23fdae1b7a"), img("photo-1525609004556-c46c7d6cf023")],
                description: "Super SUV without apology. The Urus S is a 2.2-tonne wedge that still hits 100 km/h in 3.5 seconds.",
                features: ["ANIMA", "Air suspension", "Torque vectoring"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Audi",
    country: "Germany",
    description: "Quattro traction and RS aggression. Avant for the realists, R8 for the romantics.",
    models: [
      {
        name: "RS6",
        generations: [
          {
            name: "C8",
            yearStart: 2020,
            cars: [
              {
                trim: "RS6 Avant Performance",
                year: 2024,
                bodyType: "Wagon",
                engine: "4.0L Twin-Turbo V8",
                displacement: 4.0,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "AWD",
                horsepower: 621,
                torque: 850,
                zeroToHundred: 3.4,
                topSpeed: 305,
                weight: 2075,
                dimensions: { length: 4995, width: 1951, height: 1460 },
                images: [img("photo-1606664515524-ed2f786a3bd6"), img("photo-1618843479313-40f8afb4b4d8")],
                description: "The family Trojan horse. RS6 Performance is a wagon that humiliates sports cars at midnight on an empty autobahn.",
                features: ["RS sport exhaust", "All-wheel steering", "Dynamic package plus"],
              },
            ],
          },
        ],
      },
      {
        name: "R8",
        generations: [
          {
            name: "4S",
            yearStart: 2015,
            yearEnd: 2023,
            cars: [
              {
                trim: "V10 Performance RWD",
                year: 2023,
                bodyType: "Coupe",
                engine: "5.2L Naturally Aspirated V10",
                displacement: 5.2,
                fuelType: "Petrol",
                transmission: "DCT",
                driveType: "RWD",
                horsepower: 562,
                torque: 550,
                zeroToHundred: 3.7,
                topSpeed: 329,
                weight: 1590,
                dimensions: { length: 4429, width: 1940, height: 1236 },
                images: [img("photo-1603584173870-7f23fdae1b7a"), img("photo-1606664515524-ed2f786a3bd6")],
                description: "The last Audi R8 V10. Shared DNA with the Huracán, rear-drive balance, and a scream you will not get again.",
                features: ["Audi drive select", "Magnetic ride", "Carbon sideblades"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Honda",
    country: "Japan",
    description: "High-revving honesty. Type R for the street, NSX for the hybrid supercar chapter.",
    models: [
      {
        name: "Civic",
        generations: [
          {
            name: "FL5",
            yearStart: 2023,
            cars: [
              {
                trim: "Type R",
                year: 2024,
                bodyType: "Hatchback",
                engine: "K20C1 2.0L Turbo I4",
                displacement: 2.0,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "FWD",
                horsepower: 315,
                torque: 420,
                zeroToHundred: 5.4,
                topSpeed: 272,
                weight: 1429,
                dimensions: { length: 4594, width: 1890, height: 1401 },
                images: [img("photo-1619767886558-efdc259cde1a"), img("photo-1541899481282-d53bffcf8837")],
                description: "The FL5 Type R is the front-drive reference: a 6-speed that feels milled from a single billet and aero that actually works.",
                features: ["LogR", "Adaptive dampers", "Rev-match"],
              },
            ],
          },
        ],
      },
      {
        name: "NSX",
        generations: [
          {
            name: "NC1",
            yearStart: 2016,
            yearEnd: 2022,
            cars: [
              {
                trim: "Type S",
                year: 2022,
                bodyType: "Coupe",
                engine: "3.5L Twin-Turbo V6 Hybrid",
                displacement: 3.5,
                fuelType: "Hybrid",
                transmission: "DCT",
                driveType: "AWD",
                horsepower: 600,
                torque: 667,
                zeroToHundred: 2.9,
                topSpeed: 307,
                weight: 1725,
                dimensions: { length: 4487, width: 1939, height: 1204 },
                images: [img("photo-1617531653332-bd46c24f2068"), img("photo-1619767886558-efdc259cde1a")],
                description: "The second-gen NSX Type S is Honda's hybrid supercar goodbye: SH-AWD, a twin-turbo V6, and surgical balance.",
                features: ["SH-AWD", "Carbon aero", "Track settings"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Tesla",
    country: "United States",
    description: "Electric performance as a straight-line event. Model S Plaid is the EV benchmark on REVORA.",
    models: [
      {
        name: "Model S",
        generations: [
          {
            name: "Plaid",
            yearStart: 2021,
            cars: [
              {
                trim: "Plaid",
                year: 2024,
                bodyType: "Sedan",
                engine: "Tri-Motor Electric",
                displacement: 0,
                fuelType: "Electric",
                transmission: "Single-Speed",
                driveType: "AWD",
                horsepower: 1020,
                torque: 1420,
                zeroToHundred: 2.1,
                topSpeed: 322,
                weight: 2162,
                dimensions: { length: 5021, width: 1987, height: 1431 },
                images: [img("photo-1560958089-b8a1929cea89"), img("photo-1617788138017-80ad40651399")],
                description: "Three motors, carbon-wrapped rotors, and a 0–100 that still feels like a glitch in physics.",
                features: ["Track mode", "Yoke optional", "1,000+ hp peak"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Chevrolet",
    country: "United States",
    description: "Mid-engine Corvette finally arrived. The C8 Z06 is America's accessible supercar.",
    models: [
      {
        name: "Corvette",
        generations: [
          {
            name: "C8",
            yearStart: 2020,
            cars: [
              {
                trim: "Z06",
                year: 2024,
                bodyType: "Coupe",
                engine: "LT6 5.5L Flat-Plane V8",
                displacement: 5.5,
                fuelType: "Petrol",
                transmission: "DCT",
                driveType: "RWD",
                horsepower: 670,
                torque: 623,
                zeroToHundred: 2.6,
                topSpeed: 313,
                weight: 1561,
                dimensions: { length: 4688, width: 2025, height: 1235 },
                images: [img("photo-1552519507-da3b142c6e3d"), img("photo-1494976388531-d1058494cdd8")],
                description: "The C8 Z06's LT6 is a 8,600-rpm flat-plane V8 that belongs next to European exotics, at a price that still feels American.",
                features: ["Z07 package", "Carbon aero", "Magnetic Ride 4.0"],
              },
            ],
          },
        ],
      },
    ],
  },
];

export const tuningParts = [
  {
    name: "Stage 1 ECU",
    slug: "stage-1-ecu",
    category: "ecu",
    tier: "stage1",
    exclusiveGroup: "ecu",
    description: "Optimized ignition, boost, and fueling within stock hardware limits.",
    effects: { horsepower: 45, torque: 60, reliability: -4, style: 2 },
    price: 890,
  },
  {
    name: "Stage 2 ECU",
    slug: "stage-2-ecu",
    category: "ecu",
    tier: "stage2",
    exclusiveGroup: "ecu",
    description: "Requires supporting intake and downpipe. More aggressive timing and boost.",
    effects: { horsepower: 85, torque: 110, reliability: -10, style: 4 },
    price: 1290,
  },
  {
    name: "Cold Air Intake",
    slug: "cold-air-intake",
    category: "intake",
    tier: "street",
    exclusiveGroup: null,
    description: "High-flow filter and smoother intake tract for throttle response.",
    effects: { horsepower: 12, torque: 10, style: 4 },
    price: 420,
  },
  {
    name: "Cat-Back Exhaust",
    slug: "cat-back-exhaust",
    category: "exhaust",
    tier: "street",
    exclusiveGroup: "exhaust",
    description: "Freer-flowing rear section with a deeper, more present tone.",
    effects: { horsepower: 14, torque: 12, style: 8, reliability: -1 },
    price: 1450,
  },
  {
    name: "Full Titanium Exhaust",
    slug: "full-titanium-exhaust",
    category: "exhaust",
    tier: "track",
    exclusiveGroup: "exhaust",
    description: "Lightweight full system. Loud, expensive, and worth the soundtrack.",
    effects: { horsepower: 22, torque: 16, weight: -14, style: 14, reliability: -3 },
    price: 4200,
  },
  {
    name: "High-Flow Downpipe",
    slug: "high-flow-downpipe",
    category: "downpipe",
    tier: "stage2",
    exclusiveGroup: null,
    description: "Reduces backpressure after the turbo. Best paired with Stage 2 software.",
    effects: { horsepower: 28, torque: 35, reliability: -6, style: 3 },
    price: 980,
  },
  {
    name: "Front-Mount Intercooler",
    slug: "front-mount-intercooler",
    category: "intercooler",
    tier: "stage2",
    exclusiveGroup: null,
    description: "Keeps intake temps stable on long pulls and hot days.",
    effects: { horsepower: 10, torque: 18, reliability: 4 },
    price: 760,
  },
  {
    name: "Hybrid Turbo",
    slug: "hybrid-turbo",
    category: "turbo",
    tier: "track",
    exclusiveGroup: "induction",
    description: "Larger compressor and turbine for serious power. Needs supporting mods.",
    effects: { horsepower: 130, torque: 160, reliability: -16, style: 6, topSpeed: 12 },
    price: 3900,
  },
  {
    name: "Supercharger Kit",
    slug: "supercharger-kit",
    category: "supercharger",
    tier: "track",
    exclusiveGroup: "induction",
    description: "Positive-displacement boost for NA engines. Instant throttle, extra heat.",
    effects: { horsepower: 110, torque: 90, reliability: -14, style: 10 },
    price: 6500,
  },
  {
    name: "Coilover Kit",
    slug: "coilover-kit",
    category: "suspension",
    tier: "street",
    exclusiveGroup: "suspension",
    description: "Height and damping control. Flatter through corners, firmer on broken pavement.",
    effects: { handling: 14, style: 6, reliability: -2, weight: -4 },
    price: 2100,
  },
  {
    name: "Track Suspension",
    slug: "track-suspension",
    category: "suspension",
    tier: "track",
    exclusiveGroup: "suspension",
    description: "Stiffer springs, more camber, less compromise. Built for circuit work.",
    effects: { handling: 22, style: 4, braking: 4, reliability: -6 },
    price: 3400,
  },
  {
    name: "Big Brake Kit",
    slug: "big-brake-kit",
    category: "brakes",
    tier: "street",
    exclusiveGroup: null,
    description: "Larger rotors and multi-piston calipers for fade resistance.",
    effects: { braking: 18, style: 8, weight: 8 },
    price: 2800,
  },
  {
    name: "Forged Wheels",
    slug: "forged-wheels",
    category: "wheels",
    tier: "street",
    exclusiveGroup: null,
    description: "Lighter unsprung mass. Quicker direction changes and cleaner looks.",
    effects: { weight: -12, handling: 6, style: 10 },
    price: 3200,
  },
  {
    name: "Track Semi-Slicks",
    slug: "track-semi-slicks",
    category: "tires",
    tier: "track",
    exclusiveGroup: "tires",
    description: "Maximum dry grip. Noise, wear, and wet-weather drama included.",
    effects: { handling: 12, braking: 8, reliability: -5, style: 4 },
    price: 1600,
  },
  {
    name: "Performance All-Seasons",
    slug: "performance-all-seasons",
    category: "tires",
    tier: "street",
    exclusiveGroup: "tires",
    description: "A usable compromise. Less ultimate grip, more everyday confidence.",
    effects: { handling: 3, braking: 2, reliability: 2 },
    price: 900,
  },
  {
    name: "LSD Upgrade",
    slug: "lsd-upgrade",
    category: "drivetrain",
    tier: "street",
    exclusiveGroup: null,
    description: "Puts power down on corner exit instead of lighting up one tire.",
    effects: { handling: 8, style: 2 },
    price: 1850,
  },
  {
    name: "Oil Cooler",
    slug: "oil-cooler",
    category: "cooling",
    tier: "street",
    exclusiveGroup: null,
    description: "Stabilizes oil temps on track days. The unglamorous reliability win.",
    effects: { reliability: 10 },
    price: 540,
  },
];
