import { carImg } from "./carImages.js";

/** Additional global brands to expand the REVORA catalog. */
export const extendedGlobalBrands = [
  {
    name: "Volkswagen",
    country: "Germany",
    description: "The people's car, evolved. Golf GTI and R, ID performance — VW on REVORA spans hot hatches to EVs.",
    models: [
      {
        name: "Golf",
        generations: [
          {
            name: "Mk8",
            yearStart: 2020,
            cars: [
              {
                trim: "GTI Clubsport",
                year: 2024,
                bodyType: "Hatchback",
                engine: "EA888 2.0L Turbo I4",
                displacement: 2.0,
                fuelType: "Petrol",
                transmission: "DCT",
                driveType: "FWD",
                horsepower: 300,
                torque: 400,
                zeroToHundred: 5.6,
                topSpeed: 267,
                weight: 1395,
                dimensions: { length: 4284, width: 1789, height: 1456 },
                images: carImg("vw_golf_gti_clubsport"),
                description: "Mk8 Golf GTI Clubsport — the ultimate front-drive Golf with more power and sharper aero.",
                features: ["DCC", "Akrapovic exhaust option", "Track mode"],
              },
              {
                trim: "R",
                year: 2024,
                bodyType: "Hatchback",
                engine: "EA888 2.0L Turbo I4",
                displacement: 2.0,
                fuelType: "Petrol",
                transmission: "DCT",
                driveType: "AWD",
                horsepower: 320,
                torque: 420,
                zeroToHundred: 4.7,
                topSpeed: 270,
                weight: 1550,
                dimensions: { length: 4284, width: 1789, height: 1456 },
                images: carImg("vw_golf_r"),
                description: "Golf R Mk8 with 4Motion AWD — daily usable, track capable, and still a hatchback.",
                features: ["4Motion AWD", "Drift mode", "R performance torque vectoring"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Peugeot",
    country: "France",
    description: "French design with sharp handling. From 308 to 508 — Peugeot's i-Cockpit and GT lines on REVORA.",
    models: [
      {
        name: "308",
        generations: [
          {
            name: "P5",
            yearStart: 2021,
            cars: [
              {
                trim: "GT Hybrid 225",
                year: 2024,
                bodyType: "Hatchback",
                engine: "1.6L Turbo Hybrid",
                displacement: 1.6,
                fuelType: "Hybrid",
                transmission: "Automatic",
                driveType: "FWD",
                horsepower: 225,
                torque: 360,
                zeroToHundred: 7.5,
                topSpeed: 235,
                weight: 1555,
                dimensions: { length: 4367, width: 1852, height: 1441 },
                images: carImg("peugeot_308_gt"),
                description: "New 308 GT Hybrid — French flair, plug-free hybrid torque, and one of the best cabins in class.",
                features: ["i-Cockpit", "Hybrid drive", "GT chassis"],
              },
            ],
          },
        ],
      },
      {
        name: "508",
        generations: [
          {
            name: "PSE",
            yearStart: 2019,
            cars: [
              {
                trim: "PSE",
                year: 2024,
                bodyType: "Sedan",
                engine: "1.6L Turbo Hybrid",
                displacement: 1.6,
                fuelType: "Hybrid",
                transmission: "Automatic",
                driveType: "AWD",
                horsepower: 360,
                torque: 520,
                zeroToHundred: 5.2,
                topSpeed: 250,
                weight: 1845,
                dimensions: { length: 4750, width: 1855, height: 1403 },
                images: carImg("peugeot_508_pse"),
                description: "508 Peugeot Sport Engineered — a hybrid AWD saloon that punches above its badge.",
                features: ["PSE tuning", "AWD hybrid", "Sport exhaust"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Renault",
    country: "France",
    description: "Renault Sport heritage lives on in Megane R and Alpine collaboration. Hot hatch royalty from France.",
    models: [
      {
        name: "Megane",
        generations: [
          {
            name: "IV R",
            yearStart: 2017,
            yearEnd: 2023,
            cars: [
              {
                trim: "R Trophy-R",
                year: 2022,
                bodyType: "Hatchback",
                engine: "1.8L Turbo I4",
                displacement: 1.8,
                fuelType: "Petrol",
                transmission: "DCT",
                driveType: "FWD",
                horsepower: 300,
                torque: 420,
                zeroToHundred: 5.4,
                topSpeed: 262,
                weight: 1306,
                dimensions: { length: 4362, width: 1874, height: 1447 },
                images: carImg("renault_megane_rs"),
                description: "Megane R Trophy-R — Nürburung record holder vibes in a front-drive hot hatch.",
                features: ["4Control", "Brembo brakes", "Lightweight aero"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Hyundai",
    country: "South Korea",
    description: "From i30 N to Ioniq 5 N — Hyundai's N division changed the hot hatch and EV performance conversation.",
    models: [
      {
        name: "i30",
        generations: [
          {
            name: "CN7 N",
            yearStart: 2021,
            cars: [
              {
                trim: "N",
                year: 2024,
                bodyType: "Hatchback",
                engine: "2.0L Turbo I4",
                displacement: 2.0,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "FWD",
                horsepower: 280,
                torque: 392,
                zeroToHundred: 5.9,
                topSpeed: 250,
                weight: 1495,
                dimensions: { length: 4335, width: 1795, height: 1455 },
                images: carImg("hyundai_i30n"),
                description: "i30 N with manual gearbox — pops, bangs, and a chassis that rivals the Golf GTI.",
                features: ["N Grin Shift", "Rev matching", "Electronic LSD"],
              },
            ],
          },
        ],
      },
      {
        name: "Ioniq 5",
        generations: [
          {
            name: "N",
            yearStart: 2024,
            cars: [
              {
                trim: "N",
                year: 2024,
                bodyType: "SUV",
                engine: "Dual-Motor Electric",
                displacement: 0,
                fuelType: "Electric",
                transmission: "Single-Speed",
                driveType: "AWD",
                horsepower: 641,
                torque: 770,
                zeroToHundred: 3.4,
                topSpeed: 260,
                weight: 2200,
                dimensions: { length: 4635, width: 1890, height: 1605 },
                images: carImg("hyundai_ioniq5n"),
                description: "Ioniq 5 N — the first electric hot hatch SUV. Drift mode, simulated gears, and serious power.",
                features: ["N e-Shift", "Drift mode", "800V architecture"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Kia",
    country: "South Korea",
    description: "Kia Stinger and EV6 GT prove Korea builds serious drivers' cars, not just appliances.",
    models: [
      {
        name: "Stinger",
        generations: [
          {
            name: "CK",
            yearStart: 2017,
            yearEnd: 2023,
            cars: [
              {
                trim: "GT",
                year: 2023,
                bodyType: "Sedan",
                engine: "3.3L Twin-Turbo V6",
                displacement: 3.3,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "AWD",
                horsepower: 368,
                torque: 510,
                zeroToHundred: 4.9,
                topSpeed: 270,
                weight: 1830,
                dimensions: { length: 4830, width: 1870, height: 1400 },
                images: carImg("kia_stinger_gt"),
                description: "Stinger GT — rear-drive soul in an AWD Korean grand tourer. Underrated and fast.",
                features: ["AWD", "Brembo brakes", "Adaptive dampers"],
              },
            ],
          },
        ],
      },
      {
        name: "EV6",
        generations: [
          {
            name: "GT",
            yearStart: 2022,
            cars: [
              {
                trim: "GT",
                year: 2024,
                bodyType: "SUV",
                engine: "Dual-Motor Electric",
                displacement: 0,
                fuelType: "Electric",
                transmission: "Single-Speed",
                driveType: "AWD",
                horsepower: 577,
                torque: 740,
                zeroToHundred: 3.5,
                topSpeed: 260,
                weight: 2100,
                dimensions: { length: 4680, width: 1880, height: 1550 },
                images: carImg("kia_ev6_gt"),
                description: "EV6 GT — 577 hp family crossover that embarrasses sports cars at the lights.",
                features: ["GT mode", "Drift mode", "800V charging"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Lexus",
    country: "Japan",
    description: "Toyota's luxury arm with naturally aspirated V8 drama and hybrid precision.",
    models: [
      {
        name: "LC",
        generations: [
          {
            name: "500",
            yearStart: 2017,
            cars: [
              {
                trim: "500",
                year: 2024,
                bodyType: "Coupe",
                engine: "2UR-GSE 5.0L V8",
                displacement: 5.0,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "RWD",
                horsepower: 471,
                torque: 540,
                zeroToHundred: 4.7,
                topSpeed: 270,
                weight: 1935,
                dimensions: { length: 4770, width: 1920, height: 1345 },
                images: carImg("lexus_lc500"),
                description: "LC 500 — one of the last naturally aspirated V8 GTs. Looks like concept, drives like luxury.",
                features: ["V8 NA", "10-speed auto", "Adaptive variable suspension"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Mazda",
    country: "Japan",
    description: "Jinba ittai — horse and rider as one. MX-5 remains the benchmark affordable roadster.",
    models: [
      {
        name: "MX-5",
        generations: [
          {
            name: "ND",
            yearStart: 2015,
            cars: [
              {
                trim: "RF Club",
                year: 2024,
                bodyType: "Convertible",
                engine: "2.0L Skyactiv-G I4",
                displacement: 2.0,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "RWD",
                horsepower: 184,
                torque: 205,
                zeroToHundred: 6.5,
                topSpeed: 228,
                weight: 1080,
                dimensions: { length: 3915, width: 1735, height: 1235 },
                images: carImg("mazda_mx5_nd"),
                description: "MX-5 RF Club — retractable fastback, perfect balance, and the purest driving joy per dollar.",
                features: ["Retractable roof", "Brembo option", "Limited-slip diff"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Subaru",
    country: "Japan",
    description: "Symmetrical AWD and boxer engines. WRX STI legacy lives in rally-bred DNA.",
    models: [
      {
        name: "WRX",
        generations: [
          {
            name: "VB",
            yearStart: 2022,
            cars: [
              {
                trim: "STI Sport",
                year: 2024,
                bodyType: "Sedan",
                engine: "FA24 2.4L Turbo Boxer",
                displacement: 2.4,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "AWD",
                horsepower: 271,
                torque: 350,
                zeroToHundred: 5.5,
                topSpeed: 240,
                weight: 1590,
                dimensions: { length: 4656, width: 1825, height: 1460 },
                images: carImg("subaru_wrx"),
                description: "WRX with STI Sport package — boxer turbo, AWD grip, and rally heritage in a daily sedan.",
                features: ["Symmetrical AWD", "Boxer engine", "SI-DRIVE"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Dodge",
    country: "United States",
    description: "American muscle unapologetically loud. Hellcat power in a two-door coupe.",
    models: [
      {
        name: "Challenger",
        generations: [
          {
            name: "LA",
            yearStart: 2015,
            yearEnd: 2023,
            cars: [
              {
                trim: "SRT Hellcat Redeye",
                year: 2023,
                bodyType: "Coupe",
                engine: "6.2L Supercharged HEMI V8",
                displacement: 6.2,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "RWD",
                horsepower: 797,
                torque: 959,
                zeroToHundred: 3.4,
                topSpeed: 327,
                weight: 2010,
                dimensions: { length: 5022, width: 1923, height: 1460 },
                images: carImg("dodge_challenger_hellcat"),
                description: "Challenger Hellcat Redeye — 797 hp of supercharged Americana. The last great muscle coupe.",
                features: ["Supercharged HEMI", "Line lock", "Widebody"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Volvo",
    country: "Sweden",
    description: "Scandinavian safety meets Polestar tuning. Volvo's recharge line adds electric torque.",
    models: [
      {
        name: "S60",
        generations: [
          {
            name: "Recharge",
            yearStart: 2019,
            cars: [
              {
                trim: "Polestar Engineered",
                year: 2024,
                bodyType: "Sedan",
                engine: "2.0L Turbo Hybrid I4",
                displacement: 2.0,
                fuelType: "Plug-in Hybrid",
                transmission: "Automatic",
                driveType: "AWD",
                horsepower: 455,
                torque: 680,
                zeroToHundred: 4.3,
                topSpeed: 250,
                weight: 1950,
                dimensions: { length: 4761, width: 1850, height: 1431 },
                images: carImg("volvo_s60_polestar"),
                description: "S60 Recharge Polestar Engineered — Öhlins dampers, gold Brembo calipers, hybrid AWD punch.",
                features: ["Polestar tune", "Öhlins suspension", "AWD hybrid"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Genesis",
    country: "South Korea",
    description: "Hyundai's luxury sub-brand with sharp design and serious chassis tuning.",
    models: [
      {
        name: "G70",
        generations: [
          {
            name: "RG3",
            yearStart: 2021,
            cars: [
              {
                trim: "3.3T Sport",
                year: 2024,
                bodyType: "Sedan",
                engine: "3.3L Twin-Turbo V6",
                displacement: 3.3,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "AWD",
                horsepower: 365,
                torque: 510,
                zeroToHundred: 4.5,
                topSpeed: 270,
                weight: 1750,
                dimensions: { length: 4685, width: 1850, height: 1400 },
                images: carImg("genesis_g70"),
                description: "G70 3.3T Sport — Korean 3 Series fighter with twin-turbo V6 and AWD.",
                features: ["Sport exhaust", "AWD", "Launch control"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "McLaren",
    country: "United Kingdom",
    description: "Woking supercars. Carbon tubs, twin-turbo V8s, and telepathic steering.",
    models: [
      {
        name: "720S",
        generations: [
          {
            name: "720S",
            yearStart: 2017,
            yearEnd: 2023,
            cars: [
              {
                trim: "720S",
                year: 2022,
                bodyType: "Coupe",
                engine: "M840T 4.0L Twin-Turbo V8",
                displacement: 4.0,
                fuelType: "Petrol",
                transmission: "DCT",
                driveType: "RWD",
                horsepower: 710,
                torque: 770,
                zeroToHundred: 2.9,
                topSpeed: 341,
                weight: 1283,
                dimensions: { length: 4543, width: 2161, height: 1194 },
                images: carImg("mclaren_720s"),
                description: "720S — McLaren's everyday supercar. Proactive chassis control and insane acceleration.",
                features: ["Proactive Chassis Control II", "Carbon tub", "Variable drift control"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Aston Martin",
    country: "United Kingdom",
    description: "British GT glamour. Vantage V8 thunder in a compact supercar shell.",
    models: [
      {
        name: "Vantage",
        generations: [
          {
            name: "2018",
            yearStart: 2018,
            cars: [
              {
                trim: "F1 Edition",
                year: 2023,
                bodyType: "Coupe",
                engine: "4.0L Twin-Turbo V8",
                displacement: 4.0,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "RWD",
                horsepower: 535,
                torque: 685,
                zeroToHundred: 3.6,
                topSpeed: 314,
                weight: 1530,
                dimensions: { length: 4465, width: 1942, height: 1273 },
                images: carImg("aston_martin_vantage"),
                description: "Vantage F1 Edition — AMG-sourced V8 in Aston's most focused modern chassis.",
                features: ["F1 aero", "AMG V8", "E-Diff"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Jeep",
    country: "United States",
    description: "Trackhawk absurdity — 707 hp in an SUV. Only in America.",
    models: [
      {
        name: "Grand Cherokee",
        generations: [
          {
            name: "WK2 Trackhawk",
            yearStart: 2018,
            yearEnd: 2021,
            cars: [
              {
                trim: "Trackhawk",
                year: 2021,
                bodyType: "SUV",
                engine: "6.2L Supercharged HEMI V8",
                displacement: 6.2,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "AWD",
                horsepower: 707,
                torque: 875,
                zeroToHundred: 3.5,
                topSpeed: 290,
                weight: 2360,
                dimensions: { length: 4914, width: 2068, height: 1778 },
                images: carImg("jeep_trackhawk"),
                description: "Grand Cherokee Trackhawk — Hellcat engine in a family SUV. Ludicrous and legendary.",
                features: ["Supercharged HEMI", "AWD", "Brembo brakes"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Maserati",
    country: "Italy",
    description: "Modena drama. MC20's Nettuno V6 brings F1 tech to the road.",
    models: [
      {
        name: "MC20",
        generations: [
          {
            name: "MC20",
            yearStart: 2020,
            cars: [
              {
                trim: "Cielo",
                year: 2024,
                bodyType: "Convertible",
                engine: "Nettuno 3.0L Twin-Turbo V6",
                displacement: 3.0,
                fuelType: "Petrol",
                transmission: "DCT",
                driveType: "RWD",
                horsepower: 630,
                torque: 730,
                zeroToHundred: 2.9,
                topSpeed: 320,
                weight: 1540,
                dimensions: { length: 4669, width: 1965, height: 1224 },
                images: carImg("maserati_mc20"),
                description: "MC20 Cielo — retractable glass roof, Nettuno V6, and Italian supercar theatre.",
                features: ["Nettuno V6", "Carbon monocoque", "Retractable roof"],
              },
            ],
          },
        ],
      },
    ],
  },
];
