import { carImg } from "./carImages.js";

/** Iranian automotive brands — Iran Khodro & Saipa plus domestic models. */
export const iranianBrands = [
  {
    name: "Iran Khodro",
    country: "Iran",
    description:
      "Iran's largest automaker. From Samand and Dena to Tara and Peugeot-licensed platforms — the backbone of Iranian roads on REVORA.",
    models: [
      {
        name: "Dena",
        generations: [
          {
            name: "Dena Family",
            yearStart: 2015,
            cars: [
              {
                trim: "Plus Turbo",
                year: 2024,
                bodyType: "Sedan",
                engine: "EF7 Turbo 1.7L TC",
                displacement: 1.7,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "FWD",
                horsepower: 170,
                torque: 240,
                zeroToHundred: 9.2,
                topSpeed: 210,
                weight: 1380,
                dimensions: { length: 4550, width: 1780, height: 1480 },
                images: carImg("ikco_dena_plus_turbo"),
                description:
                  "Iran Khodro's modern sedan flagship. Turbo EF7, CVT, and a cabin that finally feels a generation ahead of the old Samand era.",
                features: ["Turbo EF7", "CVT gearbox", "ABS + EBD", "Dual airbags"],
              },
              {
                trim: "Plus",
                year: 2023,
                bodyType: "Sedan",
                engine: "EF7 1.7L NA",
                displacement: 1.7,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "FWD",
                horsepower: 115,
                torque: 155,
                zeroToHundred: 11.5,
                topSpeed: 185,
                weight: 1350,
                dimensions: { length: 4550, width: 1780, height: 1480 },
                images: carImg("ikco_dena_plus"),
                description: "Naturally aspirated Dena Plus — the volume seller with simple mechanics and easy service across Iran.",
                features: ["EF7 engine", "Manual 5-speed", "Parking sensors"],
              },
            ],
          },
        ],
      },
      {
        name: "Tara",
        generations: [
          {
            name: "Tara",
            yearStart: 2021,
            cars: [
              {
                trim: "Automatic",
                year: 2024,
                bodyType: "Sedan",
                engine: "M15 1.5L I4",
                displacement: 1.5,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "FWD",
                horsepower: 113,
                torque: 145,
                zeroToHundred: 12.8,
                topSpeed: 180,
                weight: 1280,
                dimensions: { length: 4480, width: 1740, height: 1470 },
                images: carImg("ikco_tara"),
                description:
                  "Compact sedan built for Iranian cities. Tara replaced aging platforms with a cleaner design and modern safety kit.",
                features: ["Reverse camera", "Touchscreen", "Cruise control"],
              },
            ],
          },
        ],
      },
      {
        name: "Samand",
        generations: [
          {
            name: "Soren",
            yearStart: 2007,
            cars: [
              {
                trim: "ELX",
                year: 2022,
                bodyType: "Sedan",
                engine: "XU7 1.8L I4",
                displacement: 1.8,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "FWD",
                horsepower: 100,
                torque: 142,
                zeroToHundred: 13.5,
                topSpeed: 175,
                weight: 1320,
                dimensions: { length: 4520, width: 1720, height: 1460 },
                images: carImg("ikco_samand_soren"),
                description:
                  "The Samand Soren ELX — a familiar face on Iranian highways. Peugeot-derived architecture with local engineering.",
                features: ["ELX trim", "Power windows", "Factory CNG option"],
              },
            ],
          },
        ],
      },
      {
        name: "Peugeot 206",
        generations: [
          {
            name: "206",
            yearStart: 2001,
            yearEnd: 2020,
            cars: [
              {
                trim: "SD V8",
                year: 2019,
                bodyType: "Hatchback",
                engine: "TU5 1.6L I4",
                displacement: 1.6,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "FWD",
                horsepower: 105,
                torque: 142,
                zeroToHundred: 11.8,
                topSpeed: 185,
                weight: 1080,
                dimensions: { length: 3835, width: 1652, height: 1433 },
                images: carImg("ikco_peugeot_206"),
                description:
                  "The Iranian-built 206 SD — still a cult hatchback. Light, rev-happy TU5, and endless aftermarket support in Tehran.",
                features: ["TU5 engine", "Sport suspension option", "Iconic 206 styling"],
              },
            ],
          },
        ],
      },
      {
        name: "Peugeot 207i",
        generations: [
          {
            name: "207i",
            yearStart: 2012,
            cars: [
              {
                trim: "Automatic",
                year: 2023,
                bodyType: "Hatchback",
                engine: "TU5 1.6L I4",
                displacement: 1.6,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "FWD",
                horsepower: 105,
                torque: 142,
                zeroToHundred: 12.2,
                topSpeed: 180,
                weight: 1150,
                dimensions: { length: 4030, width: 1680, height: 1470 },
                images: carImg("ikco_peugeot_207i"),
                description: "207i with automatic gearbox — one of IKCO's best-selling modern hatchbacks in the Iranian market.",
                features: ["Automatic TU5", "ABS", "Bluetooth audio"],
              },
            ],
          },
        ],
      },
      {
        name: "Peugeot Pars",
        generations: [
          {
            name: "Pars",
            yearStart: 2000,
            cars: [
              {
                trim: "ELX",
                year: 2021,
                bodyType: "Sedan",
                engine: "XU7 1.8L I4",
                displacement: 1.8,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "FWD",
                horsepower: 100,
                torque: 142,
                zeroToHundred: 13.0,
                topSpeed: 178,
                weight: 1290,
                dimensions: { length: 4430, width: 1700, height: 1440 },
                images: carImg("ikco_peugeot_pars"),
                description: "Peugeot Pars ELX — the Persian sedan. Based on the 405 platform, tuned for Iranian fuel and roads.",
                features: ["XU7 engine", "ELX equipment", "Wide service network"],
              },
            ],
          },
        ],
      },
      {
        name: "Peugeot 2008",
        generations: [
          {
            name: "2008",
            yearStart: 2020,
            cars: [
              {
                trim: "Cross",
                year: 2024,
                bodyType: "SUV",
                engine: "EB2 1.2L Turbo",
                displacement: 1.2,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "FWD",
                horsepower: 130,
                torque: 230,
                zeroToHundred: 10.5,
                topSpeed: 195,
                weight: 1285,
                dimensions: { length: 4300, width: 1770, height: 1550 },
                images: carImg("ikco_peugeot_2008"),
                description: "Locally assembled 2008 Cross — compact SUV demand in Iran made this one of IKCO's crossover hits.",
                features: ["Turbo three-cylinder", "Cross cladding", "Panoramic roof option"],
              },
            ],
          },
        ],
      },
      {
        name: "Runna",
        generations: [
          {
            name: "Runna",
            yearStart: 2012,
            cars: [
              {
                trim: "Plus",
                year: 2022,
                bodyType: "Sedan",
                engine: "TU5 1.6L I4",
                displacement: 1.6,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "FWD",
                horsepower: 105,
                torque: 142,
                zeroToHundred: 12.0,
                topSpeed: 182,
                weight: 1180,
                dimensions: { length: 4270, width: 1680, height: 1490 },
                images: carImg("ikco_runna"),
                description: "Runna Plus — a compact sedan derived from the 206 platform, aimed at first-time buyers.",
                features: ["TU5 power", "Compact footprint", "Fuel efficient"],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Saipa",
    country: "Iran",
    description:
      "Saipa builds and badges everything from Pride to Shahin. High volume, national reach, and models every Iranian driver recognizes.",
    models: [
      {
        name: "Shahin",
        generations: [
          {
            name: "G",
            yearStart: 2020,
            cars: [
              {
                trim: "G",
                year: 2024,
                bodyType: "Sedan",
                engine: "M15 1.5L I4",
                displacement: 1.5,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "FWD",
                horsepower: 150,
                torque: 210,
                zeroToHundred: 10.8,
                topSpeed: 195,
                weight: 1320,
                dimensions: { length: 4660, width: 1785, height: 1495 },
                images: carImg("saipa_shahin"),
                description:
                  "Saipa's modern sedan — Shahin G with automatic gearbox. One of the most visible new Iranian cars on city streets.",
                features: ["Automatic transmission", "Keyless entry", "LED DRLs"],
              },
            ],
          },
        ],
      },
      {
        name: "Quick",
        generations: [
          {
            name: "Quick",
            yearStart: 2017,
            cars: [
              {
                trim: "R",
                year: 2024,
                bodyType: "Hatchback",
                engine: "M15 1.5L I4",
                displacement: 1.5,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "FWD",
                horsepower: 87,
                torque: 120,
                zeroToHundred: 14.5,
                topSpeed: 165,
                weight: 1050,
                dimensions: { length: 3995, width: 1645, height: 1500 },
                images: carImg("saipa_quick_r"),
                description: "Quick R — crossover-hatch styling on a lightweight platform. Saipa's answer to urban SUV demand.",
                features: ["Crossover styling", "Compact size", "Low running costs"],
              },
              {
                trim: "S",
                year: 2023,
                bodyType: "Hatchback",
                engine: "M15 1.5L I4",
                displacement: 1.5,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "FWD",
                horsepower: 87,
                torque: 120,
                zeroToHundred: 14.8,
                topSpeed: 163,
                weight: 1040,
                dimensions: { length: 3995, width: 1645, height: 1500 },
                images: carImg("saipa_quick_s"),
                description: "Quick S — the standard Quick with simpler trim but the same practical city footprint.",
                features: ["City-friendly size", "Easy parking", "Economical"],
              },
            ],
          },
        ],
      },
      {
        name: "Saina",
        generations: [
          {
            name: "S",
            yearStart: 2016,
            cars: [
              {
                trim: "S",
                year: 2023,
                bodyType: "Sedan",
                engine: "M15 1.5L I4",
                displacement: 1.5,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "FWD",
                horsepower: 87,
                torque: 120,
                zeroToHundred: 14.2,
                topSpeed: 168,
                weight: 1100,
                dimensions: { length: 4240, width: 1640, height: 1480 },
                images: carImg("saipa_saina"),
                description: "Saina S — sedan evolution of the Pride platform. Ubiquitous as a taxi and daily driver across Iran.",
                features: ["Simple mechanics", "Low parts cost", "Sedan practicality"],
              },
            ],
          },
        ],
      },
      {
        name: "Pride",
        generations: [
          {
            name: "111",
            yearStart: 1993,
            yearEnd: 2020,
            cars: [
              {
                trim: "111",
                year: 2019,
                bodyType: "Hatchback",
                engine: "1.3L I4",
                displacement: 1.3,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "FWD",
                horsepower: 65,
                torque: 95,
                zeroToHundred: 16.5,
                topSpeed: 145,
                weight: 920,
                dimensions: { length: 3595, width: 1595, height: 1470 },
                images: carImg("saipa_pride_111"),
                description:
                  "The Saipa Pride 111 — arguably the most common car in Iran. Light, simple, and endlessly repairable.",
                features: ["Ultra-light", "Minimalist", "Nationwide parts supply"],
              },
            ],
          },
          {
            name: "132",
            yearStart: 1993,
            cars: [
              {
                trim: "132",
                year: 2018,
                bodyType: "Sedan",
                engine: "1.3L I4",
                displacement: 1.3,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "FWD",
                horsepower: 65,
                torque: 95,
                zeroToHundred: 17.0,
                topSpeed: 142,
                weight: 950,
                dimensions: { length: 4050, width: 1595, height: 1470 },
                images: carImg("saipa_pride_132"),
                description: "Pride 132 sedan — the trunked Pride that dominated Iranian taxi fleets for decades.",
                features: ["Sedan body", "Low fuel use", "Easy maintenance"],
              },
            ],
          },
        ],
      },
      {
        name: "Tiba",
        generations: [
          {
            name: "Tiba 2",
            yearStart: 2014,
            cars: [
              {
                trim: "Hatchback",
                year: 2022,
                bodyType: "Hatchback",
                engine: "M15 1.5L I4",
                displacement: 1.5,
                fuelType: "Petrol",
                transmission: "Manual",
                driveType: "FWD",
                horsepower: 87,
                torque: 120,
                zeroToHundred: 14.0,
                topSpeed: 170,
                weight: 1020,
                dimensions: { length: 3945, width: 1645, height: 1500 },
                images: carImg("saipa_tiba"),
                description: "Tiba 2 hatchback — Saipa's in-house compact replacing the aging Pride for a new generation.",
                features: ["M15 engine", "Hatchback utility", "Value pricing"],
              },
            ],
          },
        ],
      },
      {
        name: "CS35",
        generations: [
          {
            name: "CS35 Plus",
            yearStart: 2019,
            cars: [
              {
                trim: "Plus",
                year: 2024,
                bodyType: "SUV",
                engine: "1.6L Turbo I4",
                displacement: 1.6,
                fuelType: "Petrol",
                transmission: "Automatic",
                driveType: "FWD",
                horsepower: 156,
                torque: 260,
                zeroToHundred: 9.8,
                topSpeed: 190,
                weight: 1380,
                dimensions: { length: 4335, width: 1825, height: 1660 },
                images: carImg("saipa_cs35"),
                description: "Changan CS35 Plus assembled by Saipa — compact turbo SUV for Iran's crossover boom.",
                features: ["Turbo engine", "Automatic", "SUV ride height"],
              },
            ],
          },
        ],
      },
    ],
  },
];
